<?
#    Installfest Webpage - a php/postgresql/apache instant Linux
#                          installfest web page and database.
#    Copyright (C) 2001 Michael Davies (michaeld@senet.com.au) & Phil Hutton (phil@hutton.sh)
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

$TITLE = "LinuxSA Installfest Web Page";
$VERSION = "0.99.4";
$DOWNLOAD_URL = "http://hutton.sh/installfest/iwp-0.99.4.tgz";

$AUTHORS = "Michael Davies & Phil Hutton";
$EMAIL = "michaeld@senet.com.au";
$DATE = "August 2001";

/* Debug Level, 0 is no errors reported, 8 is everything reported,
   9 is everything + phpinfo() */
$DEBUG_LEVEL = 0;

?>
